### ISSUE TITLE
Failure to start with Python Exception

### ISSUE THREAD

**Issue by torbenlast** [cooked/kimotor#30]
I'm running into a Python exception upon starting the Plugin.
This is on Debian Unstable with KiCAD installed as an apt package. (not a Flatpak)
I've tested both the 0.99 release and the current git version and run into the same issue:

![Screenshot-2022-12-14 17-40-49](https://user-images.githubusercontent.com/50545231/207657103-3a9e14bb-9d69-4011-92a3-21a394e5c46a.png)

Love the project.

**Comment by craigarno** [comment]
Same issue under Windows 10 Pro:

![image](https://user-images.githubusercontent.com/4262930/212975364-6be2bb99-f766-4cd1-9449-482cd79cb2b1.png)

Edition	Windows 10 Pro
Version	22H2
Installed on	‎7/‎6/‎2021
OS build	19045.2364
Experience	Windows Feature Experience Pack 120.2212.4190.0

=================

Application: KiCad (64-bit)

Version: (6.0.10), release build

Libraries:
	wxWidgets 3.2.1
	libcurl/7.86.0-DEV Schannel zlib/1.2.13

Platform: Windows 10 (build 19045), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Dec 19 2022 21:23:04
	wxWidgets: 3.2.1 (wchar_t,wx containers)
	Boost: 1.80.0
	OCC: 7.6.2
	Curl: 7.86.0-DEV
	ngspice: 38
	Compiler: Visual C++ 1929 without C++ ABI

Build settings:
	KICAD_USE_OCC=ON
	KICAD_SPICE=ON

=================

C:\Users\craig\Documents\KiCad\6.0>python --version
Python 3.9.14

=================

I am excited to give your project a try!  This looks fun, educational, and useful.

**Comment by cooked** [comment]
Hi @craigarno, @torbenlast,
I've looked into the issue.
The plugin needs to know the footprint library path variable KICAD6_FOOTPRINT_DIR to import the mounting hole footprint.
Currently  just the file kicad_common.json is checked, but that file it is populated only if the default paths have been changed at least once. If that is not the case , the plugin should look for the variables in the os environment instead of the file (see forum post https://forum.kicad.info/t/how-to-read-configured-paths-from-python/39664/5)

FIX: 
I updated the code to search the env variables first, then the file as a fallback

I've tested the fix on Debian+Flatpack only, but hopefully it will work also on windows

I'm in the process of pushing it to the plugin repo and soon v0.1.1 should be available

**Comment by cooked** [comment]
Hi @craigarno, @torbenlast,
v0.1.1 should be available in the Kicad Content Managare tomorrow Jan 23 at 12pm.

Hopefully it will fix your issue. If you test it out let me know how it goes

**Comment by craigarno** [comment]
@cooked ,
I couldn't install from PCM directly.  I get this error message:

```
Downloading package url: 'https://github.com/cooked/kimotor/releases/download/v0.1.1/kimotor-pcm.zip'
Failed to download url https://github.com/cooked/kimotor/releases/download/v0.1.1/kimotor-pcm.zip Failure when receiving data from the peer
Done.
```

After a little trial and error, I tried https://github.com/cooked/kimotor/releases/ which let me download file  **kimotor-pcm.zip** from 0.1.1.  I am able to install KiMotor from PCM using _**Install from File...**_

Once installed, I go to PCB Editor, click on the KiMotor symbol and get this dialog:
![image](https://user-images.githubusercontent.com/4262930/214455707-eef65098-6ab6-4b33-b679-d5ad63bc1a2b.png)

As you can see, not very useful if the dialog boxes can't be read.  I suspect this has to do with Windows screen scaling feature which on my primary screen is set to 175%.  It's a 4K screen only 15 inches diameter, impossible to read without a good magnifying glass at 100%.

I tried setting my primary screen to 100% and call up the KiMotor dialog again and get better results, somewhat confirming my suspicions:
![image](https://user-images.githubusercontent.com/4262930/214457394-cf833013-4c72-49d3-b7e0-c22ace0cdafd.png)

Not knowing what library builds the GUI dialog, I can't offer much more information to help.

**Comment by craigarno** [comment]
It looks like there are other issues.  I ask KiMotor to "Generate" from default values which show in the dialog and get an image which looks like it has PCB drawing issues using KiCad v6.0.10

![image](https://user-images.githubusercontent.com/4262930/214458407-8d281f15-7889-4a4d-92a7-648da325f88c.png)

**Comment by cooked** [comment]
@craigarno thanks for reporting your findings. I split the new bugs into their own issues and look into them in the coming days :+1:

**Comment by cooked** [comment]
latest code from this repo shall fix the issue
