### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by rozrabiak** [cooked/kimotor#31]
Kicad 6.0.10

![Zrzut ekranu 2023-01-10 215254](https://user-images.githubusercontent.com/73905882/211660381-f1f24eda-ab22-44a0-8831-38ce3a44e978.jpg)

**Comment by cooked** [comment]
Hi @rozrabiak ,can you provide:
- which OS are you on?
- where Kicad was installed from (download from homepage, repo or flatpak if on Linux)

thanks, that would help to troubleshoot the error

**Comment by rozrabiak** [comment]
Yeah, sorry,
Windows 11 x64.
Kicad installed from homepage.

**Comment by cooked** [comment]
Hi @rozrabiak ,
thanks for the info on your system. Additionally it would help me if you can indicate the steps that got you to the error ( for example if you changed parameters before generating or if you ran the default settings).

Thanks again

**Comment by rozrabiak** [comment]
I'm downloaded as zip file from GitHub and install zip file.
I didn't change any parameters.
When I try installing from kicad via download option - there was a file download error.

**Comment by cooked** [comment]
Hi @rozrabiak 
v0.1.1 should be available in the Kicad Content Managare tomorrow Jan 23 at 12pm.

It contains a fix for issue #30 that others are experiencing, but possibly will fix also yours.  

If you test it out let me know how it goes

**Comment by cooked** [comment]
@rozrabiak is this solved for you?

**Comment by cooked** [comment]
in between official releases, that will be available from KiCad PCM, the plugin can be installed as described here: https://github.com/cooked/kimotor/issues/39#issuecomment-1550412060
