### ISSUE TITLE
default parameters (fillet) generate bad layout on Win

### ISSUE THREAD

**Issue by cooked** [cooked/kimotor#38]
originally reported in #30 :

It looks like there are other issues.  I ask KiMotor to "Generate" from default values which show in the dialog and get an image which looks like it has PCB drawing issues using KiCad v6.0.10.  I should probably open a new issue for this input.

![image](https://user-images.githubusercontent.com/4262930/214458407-8d281f15-7889-4a4d-92a7-648da325f88c.png)

**Comment by rozrabiak** [comment]
That's true..
Kicad 6.0.11

![Zrzut ekranu 2023-02-12 132836](https://user-images.githubusercontent.com/73905882/218311212-8ea732d8-7817-4250-8701-2c7b485bfa59.png)

**Comment by cooked** [comment]
Hi @rozrabiak,
thanks for confirming. I also did run a test and so far it looks like I could reproduce the bug on Window as well, while Linux works ok.
I'll have to look into the algorithm that generates the coil layout which is the one causing this issue.

Hope to get back to you with a positive update

**Comment by HaydenHu** [comment]
> @rozrabiak as a quick workaround you can try to disable the track fillet, that is the part that is causing the issue... ![image](https://user-images.githubusercontent.com/1381353/225849624-67f5229e-8224-4c80-87ce-732d6858252e.png)
> 
> with the track fillet set to 0 you should be able to have a proper layout, until I've validated the fix to the fillet algorithm that I'm currently working on
> 
> let me know how it goes
> 
> P.S. if you are testing on kicad 7, you will still not be able to run the plugin at the moment, but I plan to add the support for the 7 this weekend

Have you solved the rounded corner algorithm?

**Comment by cooked** [comment]
> > @rozrabiak as a quick workaround you can try to disable the track fillet, that is the part that is causing the issue... ![image](https://user-images.githubusercontent.com/1381353/225849624-67f5229e-8224-4c80-87ce-732d6858252e.png)
> > with the track fillet set to 0 you should be able to have a proper layout, until I've validated the fix to the fillet algorithm that I'm currently working on
> > let me know how it goes
> > P.S. if you are testing on kicad 7, you will still not be able to run the plugin at the moment, but I plan to add the support for the 7 this weekend
> 
> Have you solved the rounded corner algorithm?

Hi @HaydenHu, unfortunately the issue is not solved. Since the bug appeared on Win, the plugin code from the repo now disables the fillet on Win OS, to prevent triggering this bug

**Comment by cooked** [comment]
fixed in 0a86122faedac84f7919117dfa3418df440ff211
don't shout it too loud!
