### ISSUE TITLE
Idea : Possibly combine the below to the current version

### ISSUE THREAD

**Issue by geekx** [cooked/kimotor#46]
https://github.com/atomic14/kicad-coil-plugins

In this repo, it has a wedge version coil generator, would also help

**Comment by cooked** [comment]
Hi @geekx,
the development version (the code in this repo master branch) got the option to pick "radial" as a strategy for coil layout. That should generate the wedges you're looking for, if I understand your question correctly.

![image](https://github.com/cooked/kimotor/assets/1381353/c4517d2f-9282-4c60-b4d2-aa53cb583bfe)

radial
![image](https://github.com/cooked/kimotor/assets/1381353/9ac63e67-18c3-4018-9407-d041e7ab803b)

parallel
![image](https://github.com/cooked/kimotor/assets/1381353/e87b74aa-e008-4aca-8150-cf899056fc2b)

**Comment by geekx** [comment]
Thanks.

**Comment by cooked** [comment]
Hey @geekx, 
yes I would advise to still use the DRC. At the current stage the plugin does not enforce any fab constraint, so having proper board settings in the project + taking care of DRC messages, are still the steps that guarantee that you meet your PCB fab capabilities.
