### ISSUE TITLE
co-located vias shall be avoided

### ISSUE THREAD

**Issue by cooked** [cooked/kimotor#51]
on motors with 4+ layers, the buried vias used to jump between layer pairs are now "co-located" (same x,y coordinates)

this is flagged as a warning by the DRC since PCB fabs might not be happy with this setting, and the tolerances on drilling a hole in the same spot multiple times might lead to failing PCBs.

to avoid this the algorithm should "stagger" the buried vias along the arc track in a way that the min hole-hole clearance is satisfied

![image](https://github.com/cooked/kimotor/assets/1381353/7bc5d558-23b5-4b47-9e87-a1639bbb40a2)

**Comment by cooked** [comment]
looking into PCB fabs capabilities it is clear that to keep the cost of low-volume boards low, blind/buried vias shall be avoided. a possible approach is to move via away from coil tracks so that regardless of the nr of layers the layer jumps can be achieved with through holes (standard vias)

![image](https://github.com/cooked/kimotor/assets/1381353/74c1cccd-c764-4069-95c6-34f265611809)

**Comment by algocrypto** [comment]
Hi,
Thank you for sharing the plugin, it looks to good for designing PCB stator. 

I am trying to build the PCB stator and am getting lot of errors, Is there any fix for this issue? 
![Screenshot 2024-03-28 at 8 43 28 AM](https://github.com/cooked/kimotor/assets/94268907/52542b8e-c1ce-4507-9d90-45ddf759d966)

**Comment by cooked** [comment]
closing. follow up in related issue #61
