### ISSUE TITLE
how to use this plugin?

### ISSUE THREAD

**Issue by hrithik254** [cooked/kimotor#62]
I noticed tht kicad official repository has the latest v0.1.1 released in 2023. I have installed it but how do I use it?

**Comment by cooked** [comment]
Hi @hrithik254 
sorry for the inconvenience. Please have a look at the installation section of the [README file](https://github.com/cooked/kimotor#installation) and give it a try to one of the two "manual installation" methods. 
The plugin version in the package manager has now fallen behind, while the code from the repo contains the fixes you need.

Before installing the new version make sure to remove the one installed via Package Manager.
