### ISSUE TITLE
Problem with parametr "Terminal pads" -> SMD. Error occurs.

### ISSUE THREAD

**Issue by MAOButNotZedong** [cooked/kimotor#70]
In line 326 "kimotor_action.py":
trm_lib = self.fp_path + 'Connector_Wire.pretty' if self.trmtype == 'THT' else 'TestPoint.pretty'
If condition TRUE:
trm_lib = self.fp_path + 'Connector_Wire.pretty'
if condition FALSE:
trm_lib = 'TestPoint.pretty'

Needs brackets:
trm_lib = self.fp_path + ('Connector_Wire.pretty' if self.trmtype == 'THT' else 'TestPoint.pretty')

**Comment by cooked** [comment]
thanks @MAOButNotZedong good catch. should be fixed now
